#include <fakedyld/fakedyld.h>

const char *strerror(int err) {
    switch(err) {
        case EUNDEFINED:            return (const char*)"Undefined error: 0";
        case EPERM:                 return (const char*)"Operation not permitted";
        case ENOENT:                return (const char*)"No such file or directory";
        case ESRCH:                 return (const char*)"No such process";
        case EINTR:                 return (const char*)"Interrupted system call";
        case EIO:                   return (const char*)"Input/output error";
        case ENXIO:                 return (const char*)"Device not configured";
        case E2BIG:                 return (const char*)"Argument list too long";
        case ENOEXEC:               return (const char*)"Exec format error";
        case EBADF:                 return (const char*)"Bad file descriptor";
        case ECHILD:                return (const char*)"No child processes";
        case EDEADLK:               return (const char*)"Resource deadlock avoided";
        case ENOMEM:                return (const char*)"Cannot allocate memory";
        case EACCES:                return (const char*)"Permission denied";
        case EFAULT:                return (const char*)"Bad address";
        case ENOTBLK:               return (const char*)"Block device required";
        case EBUSY:                 return (const char*)"Resource busy";
        case EEXIST:                return (const char*)"File exists";
        case EXDEV:                 return (const char*)"Cross-device link";
        case ENODEV:                return (const char*)"Operation not supported by device";
        case ENOTDIR:               return (const char*)"Not a directory";
        case EISDIR:                return (const char*)"Is a directory";
        case EINVAL:                return (const char*)"Invalid argument";
        case ENFILE:                return (const char*)"Too many open files in system";
        case EMFILE:                return (const char*)"Too many open files";
        case ENOTTY:                return (const char*)"Inappropriate ioctl for device";
        case ETXTBSY:               return (const char*)"Text file busy";
        case EFBIG:                 return (const char*)"File too large";
        case ENOSPC:                return (const char*)"No space left on device";
        case ESPIPE:                return (const char*)"Illegal seek";
        case EROFS:                 return (const char*)"Read-only file system";
        case EMLINK:                return (const char*)"Too many links";
        case EPIPE:                 return (const char*)"Broken pipe";
        case EDOM:                  return (const char*)"Numerical argument out of domain";
        case ERANGE:                return (const char*)"Result too large";
        case EAGAIN:                return (const char*)"Resource temporarily unavailable";
        case EINPROGRESS:           return (const char*)"Operation now in progress";
        case EALREADY:              return (const char*)"Operation already in progress";
        case ENOTSOCK:              return (const char*)"Socket operation on non-socket";
        case EDESTADDRREQ:          return (const char*)"Destination address required";
        case EMSGSIZE:              return (const char*)"Message too long";
        case EPROTOTYPE:            return (const char*)"Protocol wrong type for socket";
        case ENOPROTOOPT:           return (const char*)"Protocol not available";
        case EPROTONOSUPPORT:       return (const char*)"Protocol not supported";
        case ESOCKTNOSUPPORT:       return (const char*)"Socket type not supported";
        case ENOTSUP:               return (const char*)"Operation not supported";
        case EPFNOSUPPORT:          return (const char*)"Protocol family not supported";
        case EAFNOSUPPORT:          return (const char*)"Address family not supported by protocol family";
        case EADDRINUSE:            return (const char*)"Address already in use";
        case EADDRNOTAVAIL:         return (const char*)"Can't assign requested address";
        case ENETDOWN:              return (const char*)"Network is down";
        case ENETUNREACH:           return (const char*)"Network is unreachable";
        case ENETRESET:             return (const char*)"Network dropped connection on reset";
        case ECONNABORTED:          return (const char*)"Software caused connection abort";
        case ECONNRESET:            return (const char*)"Connection reset by peer";
        case ENOBUFS:               return (const char*)"No buffer space available";
        case EISCONN:               return (const char*)"Socket is already connected";
        case ENOTCONN:              return (const char*)"Socket is not connected";
        case ESHUTDOWN:             return (const char*)"Can't send after socket shutdown";
        case ETOOMANYREFS:          return (const char*)"Too many references: can't splice";
        case ETIMEDOUT:             return (const char*)"Operation timed out";
        case ECONNREFUSED:          return (const char*)"Connection refused";
        case ELOOP:                 return (const char*)"Too many levels of symbolic links";
        case ENAMETOOLONG:          return (const char*)"File name too long";
        case EHOSTDOWN:             return (const char*)"Host is down";
        case EHOSTUNREACH:          return (const char*)"No route to host";
        case ENOTEMPTY:             return (const char*)"Directory not empty";
        case EPROCLIM:              return (const char*)"Too many processes";
        case EUSERS:                return (const char*)"Too many users";
        case EDQUOT:                return (const char*)"Disc quota exceeded";
        case ESTALE:                return (const char*)"Stale NFS file handle";
        case EREMOTE:               return (const char*)"Too many levels of remote in path";
        case EBADRPC:               return (const char*)"RPC struct is bad";
        case ERPCMISMATCH:          return (const char*)"RPC version wrong";
        case EPROGUNAVAIL:          return (const char*)"RPC prog. not avail";
        case EPROGMISMATCH:         return (const char*)"Program version wrong";
        case EPROCUNAVAIL:          return (const char*)"Bad procedure for program";
        case ENOLCK:                return (const char*)"No locks available";
        case ENOSYS:                return (const char*)"Function not implemented";
        case EFTYPE:                return (const char*)"Inappropriate file type or format";
        case EAUTH:                 return (const char*)"Authentication error";
        case ENEEDAUTH:             return (const char*)"Need authenticator";
        case EPWROFF:               return (const char*)"Device power is off";
        case EDEVERR:               return (const char*)"Device error";
        case EOVERFLOW:             return (const char*)"Value too large to be stored in data type";
        case EBADEXEC:              return (const char*)"Bad executable (or shared library)";
        case EBADARCH:              return (const char*)"Bad CPU type in executable";
        case ESHLIBVERS:            return (const char*)"Shared library version mismatch";
        case EBADMACHO:             return (const char*)"Malformed Mach-o file";
        case ECANCELED:             return (const char*)"Operation canceled";
        case EIDRM:                 return (const char*)"Identifier removed";
        case ENOMSG:                return (const char*)"No message of desired type";
        case EILSEQ:                return (const char*)"Illegal byte sequence";
        case ENOATTR:               return (const char*)"Attribute not found";
        case EBADMSG:               return (const char*)"Bad message";
        case EMULTIHOP:             return (const char*)"EMULTIHOP (Reserved)";
        case ENODATA:               return (const char*)"No STREAM resources";
        case ENOLINK:               return (const char*)"ENOLINK (Reserved)";
        case ENOSR:                 return (const char*)"No STREAM resources";
        case ENOSTR:                return (const char*)"Not a STREAM";
        case EPROTO:                return (const char*)"Protocol error";
        case ETIME:                 return (const char*)"STREAM ioctl timeout";
        case EOPNOTSUPP:            return (const char*)"Operation not supported on socket";
        case ENOPOLICY:             return (const char*)"Policy not found";
        case ENOTRECOVERABLE:       return (const char*)"State not recoverable";
        case EOWNERDEAD:            return (const char*)"Previous owner died";
        case EQFULL:                return (const char*)"Interface output queue is full";
        default:                    return (const char*)"Unknown Error";
    }
}
